version: "3.9"

services:
  # traefik:
  #       image: traefik:v2.10
  #       container_name: traefik
  #       command:
  #         - --api.insecure=true
  #         - --providers.docker=true
  #         - --entrypoints.web.address=:80
  #       ports:
  #         - "80:80" # HTTP port
  #         - "8080:8080" # Traefik dashboard
  #       volumes:
  #         - /var/run/docker.sock:/var/run/docker.sock # To communicate with the Docker daemon
  #       networks:
  #         - web
  # front:
  #   container_name: front
  #   image: front
  #   build:
  #     context: .
  #     dockerfile: front.dockerfile
  #   restart: always
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     GROQ_API_KEY: ${GROQ_API_KEY}
  #     NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
  #     CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
  #     API_BASE_URL: ${API_BASE_URL}
  #     NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
  #   labels:
  #     - "traefik.http.routers.front.rule=Host(`test.navong.xyz`)"
  #   depends_on:
  #     - back
  #   networks:
  #     - traefik-network

  back:
    container_name: back
    image: back
    # ports:
    #   # - "4001:4000"
    build:
      context: .
      dockerfile: server/back.dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    labels:
      - "traefik.http.routers.back.rule=(Host(`quotenextjs.navong.xyz`) && PathPrefix(`/api`))"
    networks:
      - traefik-network
    restart: always

networks:
  traefik-network:
    external: true









